### ISSUE TITLE
uv.h: No such file or directory

### ISSUE THREAD

**Issue by MrGoldenpioche** [alephium/amd-miner#1]
After the git clone, trying to compile the source using "make" command and got this error : 

`src/main.cc:11:10: fatal error: uv.h: No such file or directory
#include "uv.h"
compilation terminated
Makefile:13 recipe for target linux-gpu failed`

**Comment by polarker** [comment]
> After the git clone, trying to compile the source using "make" command and got this error :
> 
> `src/main.cc:11:10: fatal error: uv.h: No such file or directory #include "uv.h" compilation terminated Makefile:13 recipe for target linux-gpu failed`

Could you try the `get-miner.sh` script, which will install libuv libs ?

**Comment by MrGoldenpioche** [comment]
Thank you. After installing libuv1-dev from get-miner.sh, still another error: 

`
In file included from src/worker.h:15:0,
from src/main.cc:14:
src/opencl_util.h:9:10: fatal error: CL/cl.h: No such file or directory
#include <CL/cl.h>
`
Maybe an important information, I am testing on HiveOS, not a "classical" linux distribution

**Comment by polarker** [comment]
You will need to
1. download `amdpro` first: [http://download.hiveos.farm/drivers/amdgpu-pro-20.40-1147287-ubuntu-18.04.tar.xz](http://download.hiveos.farm/drivers/amdgpu-pro-20.40-1147287-ubuntu-18.04.tar.xz)
2. uncompress it and run `amdgpu-pro-install --opencl=legacy,pal --headless`
3. run `sudo apt-get install opencl-headers`

**Comment by MrGoldenpioche** [comment]
I just installed the opencl-headers and the compilation passed successfully :-) Thank you for your precious help
